/* Automation rules — backed by /api/automation/rules. */
let automationRows = [];
function automationActive(a) { return a.isActive ?? a.active ?? false; }
const AUTOMATION_TRIGGERS = ["STOCK_BELOW_THRESHOLD", "ORDER_DELIVERED", "CART_ABANDONED", "RETURN_UPDATE", "CAMPAIGN_EVENT"];
const AUTOMATION_ACTIONS = ["SEND_EMAIL", "SEND_WHATSAPP", "CREATE_NOTIFICATION", "ADD_TO_SEGMENT"];
function automationLabel(v) { return (v || "").replaceAll("_", " ").toLowerCase().replace(/\b\w/g, c => c.toUpperCase()); }
async function renderAutomation() {
  $("#content").innerHTML = `<div class="page-head"><div><div class="page-eyebrow">Workflows</div><h1 class="page-title">Automation Center</h1><p class="page-sub">Loading automations…</p></div><div class="page-actions"><a class="btn btn-blue" href="builder.html">+ New automation</a></div></div><div id="automation-root"><div class="empty-state">Loading…</div></div>`;
  try { automationRows = await api.automation.list() || []; drawAutomation(); } catch (e) { $("#automation-root").innerHTML = `<div class="empty-state"><strong>Couldn't load automations.</strong><br>${escapeHtml(e.message)}</div>`; }
}
function drawAutomation() {
  const active = automationRows.filter(automationActive).length;
  $("#automation-root").innerHTML = `<p class="page-sub">${active} of ${automationRows.length} automations active across inventory, orders, and customer touchpoints.</p><div id="automation-list">${automationRows.length ? automationRows.map(a => `<div class="automation-row"><div class="automation-left"><div class="automation-ico">⚙️</div><div><div class="automation-title">${escapeHtml(a.name)}</div><div class="automation-sub">Trigger: ${automationLabel(a.triggerType)} · Condition: ${escapeHtml(a.conditionText || "Any")} · Action: ${automationLabel(a.actionType)}</div></div></div><div class="action-group"><a class="icon-action" title="Edit" href="builder.html?id=${a.id}">✎</a><button class="icon-action" title="Run log" onclick="viewRunLog(${a.id})">📜</button><button class="icon-action" title="Delete" onclick="deleteAutomation(${a.id})">🗑</button><button class="toggle ${automationActive(a) ? "on" : ""}" onclick="toggleAutomation(${a.id})"></button></div></div>`).join("") : `<div class="empty-state">No automation rules configured.</div>`}</div><div class="card mt-24"><div class="card-head"><h3>Trigger History</h3></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Automation</th><th>Trigger</th><th>Total Runs</th><th>Status</th><th></th></tr></thead><tbody>${automationRows.map(a => `<tr><td class="cell-strong">${escapeHtml(a.name)}</td><td>${automationLabel(a.triggerType)}</td><td>${Number(a.runCount || 0).toLocaleString()}</td><td>${automationActive(a) ? '<span class="badge green">Active</span>' : '<span class="badge gray">Paused</span>'}</td><td><button class="btn btn-sm btn-ghost" onclick="viewRunLog(${a.id})">View log</button></td></tr>`).join("")}</tbody></table></div></div>`;
}
function toggleAutomation(id) { api.automation.toggle(id).then(() => { toast("Automation status updated.", "success"); renderAutomation(); }).catch(e => toast(e.message, "error")); }
function viewRunLog(id) { const a = automationRows.find(x => Number(x.id) === Number(id)); if (!a) return; openModal({ title: "Run log — " + a.name, hideFooter: true, bodyHtml: `<div id="run-log-root" class="empty-state">Loading…</div>` }); api.automation.runLog(id).then(log => { $("#run-log-root").innerHTML = log.length ? log.map(l => `<div class="settings-row"><div class="settings-row-title">${escapeHtml(l.result)}</div><span class="text-muted">${l.ranAt ? fmtDateTime(new Date(l.ranAt)) : "—"}</span></div>`).join("") : "No runs recorded."; }).catch(e => { $("#run-log-root").textContent = e.message; }); }
function deleteAutomation(id) { openModal({ title: "Delete automation", danger: true, confirmLabel: "Delete rule", bodyHtml: `<p>This automation rule will stop running immediately and can't be recovered.</p>`, onSubmit: () => api.automation.remove(id).then(() => { toast("Automation rule deleted.", "success"); renderAutomation(); }).catch(e => toast(e.message, "error")) }); }
async function renderRuleBuilderPage(id) {
  let a = null; if (id) { try { a = await api.automation.get(id); } catch (e) { toast(e.message, "error"); } }
  openPage({ title: a ? "Edit automation — " + a.name : "New automation", eyebrow: "Workflows", subtitle: "Define a trigger, an optional condition, and the action to run.", backHref: "index.html", wide: true, confirmLabel: a ? "Save rule" : "Activate rule", bodyHtml: `<div class="form-grid"><div class="form-field full"><label>Rule name</label><input name="name" value="${a ? escapeHtml(a.name) : ""}" required></div><div class="form-field full"><label>1. Trigger</label><select name="triggerType">${AUTOMATION_TRIGGERS.map(v => `<option value="${v}" ${a && a.triggerType === v ? "selected" : ""}>${automationLabel(v)}</option>`).join("")}</select></div><div class="form-field full"><label>2. Condition (optional)</label><input name="conditionText" value="${a ? escapeHtml(a.conditionText || "") : ""}></div><div class="form-field full"><label>3. Action</label><select name="actionType">${AUTOMATION_ACTIONS.map(v => `<option value="${v}" ${a && a.actionType === v ? "selected" : ""}>${automationLabel(v)}</option>`).join("")}</select></div></div>`, onSubmit: data => { const request = { name: data.name, triggerType: data.triggerType, conditionText: data.conditionText || null, actionType: data.actionType }; const op = a ? api.automation.update(a.id, request) : api.automation.create(request); op.then(() => { toast(a ? "Automation rule updated." : "Automation rule created and activated.", "success"); location.href = "index.html"; }).catch(e => toast(e.message, "error")); } });
}
function initAutomationIndex() { renderAutomation(); }
function initAutomationBuilder() { renderRuleBuilderPage(getQueryParam("id")); }