/* Competitor analysis — backed by /api/competitors. */
let competitorRows = [];
let competitorProducts = [];

function competitorName(d) { return d.competitorName || d.competitor || "Unknown competitor"; }
function competitorThreshold(d) { return d.alertThresholdPct ?? d.alertThreshold ?? 0; }
function renderCompetitor() {
  $("#content").innerHTML = `<div class="page-head"><div><div class="page-eyebrow">Market intelligence</div><h1 class="page-title">Competitor Analysis</h1><p class="page-sub">Loading tracked competitor listings…</p></div><div class="page-actions"><button class="btn btn-blue" id="add-competitor-btn">+ Add competitor product</button></div></div><div id="competitor-root"><div class="empty-state">Loading…</div></div>`;
  Promise.all([api.competitors.list(), api.products.list()]).then(([rows, products]) => {
    competitorRows = rows || []; competitorProducts = products || []; drawCompetitor();
  }).catch(e => { $("#competitor-root").innerHTML = `<div class="empty-state"><strong>Couldn't load competitor data.</strong><br>${escapeHtml(e.message)}</div>`; });
  $("#add-competitor-btn").addEventListener("click", openAddCompetitorModal);
}
function drawCompetitor() {
  const avg = key => competitorRows.length ? competitorRows.reduce((s, d) => s + Number(d[key] || 0), 0) / competitorRows.length : 0;
  $("#competitor-root").innerHTML = `<div class="grid grid-4">${kpiCard("Your Avg. Price", moneyDec(avg("yourPrice")), "", "up", "🏷️")}${kpiCard("Market Avg. Price", moneyDec(avg("competitorPrice")), "", "up", "🎯")}${kpiCard("Listings Tracked", competitorRows.length, "", "up", "📚")}${kpiCard("Competitors Monitored", new Set(competitorRows.map(competitorName)).size, "", "up", "🕵️")}</div><div class="card mt-24"><div class="card-head"><h3>Price Comparison &amp; Market Position</h3></div><div class="table-wrap" style="border:none;"><table class="data-table"><thead><tr><th>Category</th><th>Linked Product</th><th>Your Price</th><th>Top Competitor</th><th>Competitor Price</th><th>Alert at</th><th>Trend</th><th></th></tr></thead><tbody>${competitorRows.length ? competitorRows.map(d => `<tr><td class="cell-strong">${escapeHtml(d.category || "—")}</td><td class="text-muted">${escapeHtml(d.linkedProductName || "—")}</td><td>${moneyDec(d.yourPrice)}</td><td>${escapeHtml(competitorName(d))}</td><td>${moneyDec(d.competitorPrice)}</td><td>${competitorThreshold(d)}%</td><td>${trendBadge(d.trend)}</td><td><div class="action-group"><a class="btn btn-sm btn-ghost" href="detail.html?id=${d.id}">History</a><button class="btn btn-sm btn-ghost" onclick="setAlertThreshold(${d.id})">Alert</button><button class="btn btn-sm btn-blue" onclick="repriceProduct(${d.id})">Reprice</button></div></td></tr>`).join("") : `<tr><td colspan="8"><div class="empty-state">No competitor listings tracked yet.</div></td></tr>`}</tbody></table></div></div>`;
}
function trendBadge(t) { return t === "up" ? '<span class="badge red">▲ Rising</span>' : t === "down" ? '<span class="badge green">▼ Falling</span>' : '<span class="badge gray">— Flat</span>'; }
function openAddCompetitorModal() {
  openModal({ title: "Add competitor product", confirmLabel: "Start tracking", bodyHtml: `<div class="form-grid"><div class="form-field full"><label>Competitor name</label><input name="competitorName" required></div><div class="form-field full"><label>Listing URL / reference</label><input name="competitorListingRef"></div><div class="form-field full"><label>Competitor price (INR)</label><input name="competitorPrice" type="number" step="any" required></div><div class="form-field full"><label>Link to your product</label><select name="linkedProductId">${competitorProducts.map(p => `<option value="${p.id}">${escapeHtml(p.name)} (${escapeHtml(p.category || "")})</option>`).join("")}</select></div></div>`, onSubmit: data => api.competitors.add({ linkedProductId: Number(data.linkedProductId), competitorName: data.competitorName, competitorListingRef: data.competitorListingRef, competitorPrice: Number(data.competitorPrice) }).then(() => { toast("Now tracking competitor pricing.", "success"); renderCompetitor(); }).catch(e => toast(e.message, "error")) });
}
function findCompetitor(id) { return competitorRows.find(d => Number(d.id) === Number(id)); }
function setAlertThreshold(id) { const d = findCompetitor(id); if (!d) { api.competitors.get(id).then(row => { competitorRows.push(row); setAlertThreshold(id); }).catch(e => toast(e.message, "error")); return; } openModal({ title: "Set alert threshold — " + (d.category || ""), confirmLabel: "Save threshold", bodyHtml: `<div class="form-field full"><label>Alert when price gap exceeds (%)</label><input name="threshold" type="number" min="1" max="100" value="${competitorThreshold(d)}" required></div>`, onSubmit: data => api.competitors.setThreshold(id, Number(data.threshold)).then(() => { toast("Alert threshold saved.", "success"); renderCompetitor(); }).catch(e => toast(e.message, "error")) }); }
function repriceProduct(id) { const d = findCompetitor(id); if (!d) { api.competitors.get(id).then(row => { competitorRows.push(row); repriceProduct(id); }).catch(e => toast(e.message, "error")); return; } openModal({ title: "Reprice — " + (d.linkedProductName || ""), confirmLabel: "Update price", bodyHtml: `<p class="text-muted">${escapeHtml(competitorName(d))} is priced at ${moneyDec(d.competitorPrice)}. Your product is ${moneyDec(d.yourPrice)}.</p><div class="form-field full mt-8"><label>New price (INR)</label><input name="price" type="number" step="any" value="${d.yourPrice}" required></div>`, onSubmit: data => api.competitors.reprice(id, Number(data.price)).then(() => { toast("Price updated.", "success"); renderCompetitor(); }).catch(e => toast(e.message, "error")) }); }
async function renderCompetitorDetailPage(id) {
  openPage({ title: "Loading…", eyebrow: "Market intelligence", backHref: "index.html", hideFooter: true, wide: true, bodyHtml: `<div id="competitor-detail-root"><div class="empty-state">Loading…</div></div>` });
  try { const d = await api.competitors.get(id), history = await api.competitors.history(id); $(".page-title").textContent = "Price history — " + (d.category || "Listing"); $("#competitor-detail-root").innerHTML = `<p class="text-muted">Your price vs. ${escapeHtml(competitorName(d))}.</p>${lineChartSVG((history || []).map((h, i) => ({ label: h.recordedAt ? fmtDate(new Date(h.recordedAt)) : `#${i + 1}`, value: Number(h.yourPrice) })), { height: 180 })}<div class="table-wrap mt-16"><table class="data-table"><thead><tr><th>Date</th><th>Your Price</th><th>Competitor</th><th>Gap</th></tr></thead><tbody>${(history || []).map(h => `<tr><td>${h.recordedAt ? fmtDate(new Date(h.recordedAt)) : "—"}</td><td>${moneyDec(h.yourPrice)}</td><td>${moneyDec(h.competitorPrice)}</td><td>${Number(h.yourPrice) > Number(h.competitorPrice) ? '<span class="badge red">Higher</span>' : '<span class="badge green">Lower</span>'}</td></tr>`).join("") || `<tr><td colspan="4">No price history recorded.</td></tr>`}</tbody></table></div><div class="modal-foot"><button class="btn" onclick="setAlertThreshold(${d.id})">Set alert threshold</button><button class="btn btn-blue" onclick="repriceProduct(${d.id})">Reprice product</button></div>`; } catch (e) { $("#competitor-detail-root").innerHTML = `<div class="empty-state"><strong>Couldn't load history.</strong><br>${escapeHtml(e.message)}</div>`; }
}
function initCompetitorsIndex() { renderCompetitor(); }
function initCompetitorDetail() { renderCompetitorDetailPage(getQueryParam("id")); }