package com.rastudio.commerce.auth;
import com.rastudio.commerce.common.ApiException; import com.rastudio.commerce.organization.*; import com.rastudio.commerce.security.JwtService; import com.rastudio.commerce.user.*; import java.nio.charset.StandardCharsets; import java.security.*; import java.time.*; import java.util.*; import org.springframework.beans.factory.annotation.Value; import org.springframework.http.HttpStatus; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class AuthService { private final AppUserRepository users; private final OrganizationRepository organizations; private final SystemConfigRepository configs; private final RefreshTokenRepository refreshTokens; private final PasswordEncoder encoder; private final JwtService jwt; private final long refreshDays;
 public AuthService(AppUserRepository users,OrganizationRepository organizations,SystemConfigRepository configs,RefreshTokenRepository refreshTokens,PasswordEncoder encoder,JwtService jwt,@Value("${app.jwt.refresh-days}") long refreshDays){this.users=users;this.organizations=organizations;this.configs=configs;this.refreshTokens=refreshTokens;this.encoder=encoder;this.jwt=jwt;this.refreshDays=refreshDays;}
 @Transactional public RegisterResult register(RegisterRequest r){if(users.findFirstByEmailIgnoreCaseOrderById(r.email()).isPresent())throw new ApiException(HttpStatus.CONFLICT,"EMAIL_EXISTS","An account with this email already exists");var o=new Organization();o.name=r.organizationName();o.industry=r.industry();o.businessSize=r.businessSize();o.currency=r.currency()==null?"INR":r.currency();o=organizations.save(o);var u=new AppUser();u.organizationId=o.id;u.fullName=r.fullName();u.email=r.email().trim().toLowerCase();u.passwordHash=encoder.encode(r.password());u.role=UserRole.BUSINESS_OWNER_ADMIN;u.status=UserStatus.PENDING;u=users.save(u);var c=new SystemConfig();c.organizationId=o.id;c.currency=o.currency;configs.save(c);return new RegisterResult(user(u),jwt.verification(u));}
 @Transactional public UserResponse verify(String token){try {var c=jwt.claims(token);if(!"verify-email".equals(c.get("type",String.class)))throw new IllegalArgumentException();var u=users.findById(Long.valueOf(c.getSubject())).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"USER_NOT_FOUND","User not found"));u.status=UserStatus.ACTIVE;u.emailVerifiedAt=LocalDateTime.now();return user(users.save(u));}catch(ApiException e){throw e;}catch(Exception e){throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_VERIFICATION_TOKEN","Verification link is invalid or expired");}}
 @Transactional public AuthResponse login(LoginRequest r){var u=users.findFirstByEmailIgnoreCaseOrderById(r.email()).orElseThrow(()->new ApiException(HttpStatus.UNAUTHORIZED,"INVALID_CREDENTIALS","Invalid email or password"));if(!encoder.matches(r.password(),u.passwordHash))throw new ApiException(HttpStatus.UNAUTHORIZED,"INVALID_CREDENTIALS","Invalid email or password");if(u.status==UserStatus.DEACTIVATED)throw new ApiException(HttpStatus.FORBIDDEN,"ACCOUNT_DEACTIVATED","This account has been deactivated");if(u.status!=UserStatus.ACTIVE||u.emailVerifiedAt==null)throw new ApiException(HttpStatus.FORBIDDEN,"EMAIL_NOT_VERIFIED","Verify your email before signing in");u.lastLoginAt=LocalDateTime.now();users.save(u);return issue(u);}
 @Transactional public AuthResponse refresh(String raw){var t=refreshTokens.findByTokenHashAndRevokedFalse(hash(raw)).orElseThrow(()->new ApiException(HttpStatus.UNAUTHORIZED,"INVALID_REFRESH_TOKEN","Refresh token is invalid"));if(t.expiresAt.isBefore(LocalDateTime.now())){t.revoked=true;refreshTokens.save(t);throw new ApiException(HttpStatus.UNAUTHORIZED,"REFRESH_TOKEN_EXPIRED","Refresh token has expired");}t.revoked=true;refreshTokens.save(t);var u=users.findById(t.userId).orElseThrow(()->new ApiException(HttpStatus.UNAUTHORIZED,"USER_NOT_FOUND","User no longer exists"));if(u.status!=UserStatus.ACTIVE)throw new ApiException(HttpStatus.FORBIDDEN,"ACCOUNT_INACTIVE","Account is not active");return issue(u);}
 @Transactional public void logout(Long userId,String raw){refreshTokens.findByTokenHashAndRevokedFalse(hash(raw)).filter(t->t.userId.equals(userId)).ifPresent(t->{t.revoked=true;refreshTokens.save(t);});}
 public UserResponse me(Long id){return user(users.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"USER_NOT_FOUND","User not found")));}
 // Used by UserService.acceptInvitation() so a just-accepted team member is
 // signed straight in (matches the workflow doc: "Accepts invite, sets
 // password, logs in") without duplicating refresh-token issuance logic here.
 public AuthResponse issueSession(AppUser u){return issue(u);}
 private AuthResponse issue(AppUser u){String raw=randomToken();var t=new RefreshToken();t.userId=u.id;t.tokenHash=hash(raw);t.expiresAt=LocalDateTime.now().plusDays(refreshDays);refreshTokens.save(t);return new AuthResponse(jwt.access(u),raw,user(u));} private static String randomToken(){byte[] b=new byte[48];new SecureRandom().nextBytes(b);return Base64.getUrlEncoder().withoutPadding().encodeToString(b);} private static String hash(String s){try{return Base64.getEncoder().encodeToString(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}} private UserResponse user(AppUser u){return new UserResponse(u.id,u.organizationId,u.fullName,u.email,u.role.name(),u.status.name(),u.emailVerifiedAt);}
 public record RegisterRequest(@jakarta.validation.constraints.NotBlank String organizationName,String industry,String businessSize,String currency,@jakarta.validation.constraints.NotBlank String fullName,@jakarta.validation.constraints.Email @jakarta.validation.constraints.NotBlank String email,@jakarta.validation.constraints.Size(min=8) String password){} public record LoginRequest(@jakarta.validation.constraints.Email @jakarta.validation.constraints.NotBlank String email,@jakarta.validation.constraints.NotBlank String password){} public record RegisterResult(UserResponse user,String verificationToken){} public record AuthResponse(String accessToken,String refreshToken,UserResponse user){} public record UserResponse(Long id,Long organizationId,String fullName,String email,String role,String status,LocalDateTime emailVerifiedAt){}
}